// Generated by https://quicktype.io

export interface News {
    id:        number;
    title:     string;
    url:       string;
    time:      string;
    logo_src:  string;
    image_src: string;
    topic:     string;
    language:  string;
}
